# Translations template for COVID-19 Bot.
# Copyright (C) 2020 ORGANIZATION
# This file is distributed under the same license as the COVID-19 Bot
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2020.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: COVID-19 Bot v5.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2020-12-20 15:59-0700\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.8.0\n"

#: ../cogs/autoupdater.py:53
msgid ""
"‚ùå Did you really try to set the autoupdater delay to more than a year? "
"Oi. Anyways, that isn't allowed. Try again with a more reasonable delay."
msgstr ""

#: ../cogs/autoupdater.py:62
msgid ""
"‚ùå You already have a autoupdater set in this channel! Remove it with "
"`/disable_updates` and try again!"
msgstr ""

#: ../cogs/autoupdater.py:70
msgid ""
"‚ö† You're setting a delay longer than 1 day! Are you sure you want to do "
"this? To confirm, type `ok` within 15 seconds."
msgstr ""

#: ../cogs/autoupdater.py:75
msgid "Action cancelled. Set up a new autoupdater with `/autoupdate <delay>`."
msgstr ""

#: ../cogs/autoupdater.py:78
msgid "Continuing setup..."
msgstr ""

#: ../cogs/autoupdater.py:83
msgid ""
"You're setting the autoupdater to less than 10 minutes delay. I'll skip "
"the check because you are a premium guild/user. <3 from 0/0#0001"
msgstr ""

#: ../cogs/autoupdater.py:86
msgid ""
"‚ùå You can't set the autoupdater delay to less than 10 minutes unless you "
"are a premium guild.\n"
"Hint: there's no point in setting it to less than 10 minutes due to the "
"fact the stats updater only fires once every 10 minutes. If you really "
"want to get a shorter delay (no point in doing so), check out the "
"`/donate` command."
msgstr ""

#: ../cogs/autoupdater.py:95
msgid ""
"‚ùå Failed to get a ISO2 code for the country! `/list` will show you a list"
" of countries and their IDs."
msgstr ""

#: ../cogs/autoupdater.py:117
msgid "‚úÖ Posting stats for {0} in this channel every {1}."
msgstr ""

#: ../cogs/autoupdater.py:128
msgid "‚úÖ Disabled autoupdates in this channel."
msgstr ""

#: ../cogs/autoupdater.py:130 ../cogs/autoupdater.py:139
msgid "‚ùå You don't have a autoupdater set here!"
msgstr ""

#: ../cogs/autoupdater.py:144
msgid "‚úÖ Forcing a update sometime in the next minute."
msgstr ""

#: ../cogs/autoupdater.py:158
msgid "‚úÖ Next update: {0}"
msgstr ""

#: ../cogs/autoupdater.py:235
msgid ""
"I'm having a issue with finding the country name here! Here's what I'm "
"showing: {trying}"
msgstr ""

#: ../cogs/background_updates.py:23
msgid "Stopping task..."
msgstr ""

#: ../cogs/background_updates.py:25
msgid "Task has been sent a stop signal. Waiting 10 seconds..."
msgstr ""

#: ../cogs/background_updates.py:27
msgid "Sending terminate signal..."
msgstr ""

#: ../cogs/background_updates.py:29
msgid "Task has been killed. Starting now..."
msgstr ""

#: ../cogs/background_updates.py:32
msgid "Task has been sent a start signal."
msgstr ""

#: ../cogs/background_updates.py:34
msgid "Task restarted!"
msgstr ""

#: ../cogs/covid.py:63
msgid ""
"A fatal error has happened! The world data seems to have gone missing. "
"Please let a mod in the bot's support server know."
msgstr ""

#: ../cogs/covid.py:76
msgid "Didn't find any continents with that name!"
msgstr ""

#: ../cogs/covid.py:91
msgid "Use the `{0}covid world` command instead."
msgstr ""

#: ../cogs/covid.py:95
msgid ""
"Didn't find a country with that name, or the country has no cases! Try "
"searching for the name with `{0}list country`.\n"
"Hint: if you're looking for North or South Korea, try `{0}covid KP` or "
"`{0}covid KR` for North and South Korea, respectively!"
msgstr ""

#: ../cogs/covid.py:101
msgid ""
"Didn't find a country with that name, or the country has no cases! Try "
"searching for the name with `{0}list country`."
msgstr ""

#: ../cogs/covid.py:105
msgid "You've used a incorrect command: try `{0}covid {1}`"
msgstr ""

#: ../cogs/covid.py:118
msgid "You haven't split the country name and province with a `; `!"
msgstr ""

#: ../cogs/covid.py:121
msgid ""
"You've placed too many `; ` in your message! You can use only one to "
"split the country and province names! For help, run `{0}help covid "
"province`!"
msgstr ""

#: ../cogs/covid.py:133
msgid ""
"Couldn't find a country with that ID (`/list` for a list of IDs) or the "
"country has no cases!"
msgstr ""

#: ../cogs/covid.py:137
msgid ""
"Couldn't find a province with that name! If you're looking for US states,"
" see the `{0}covid states` command."
msgstr ""

#: ../cogs/covid.py:143
msgid ""
"Something went wrong, I can't find today's stats! I'm currently trying to"
" find stats for {0}!"
msgstr ""

#: ../cogs/covid.py:154
msgid "You need to specify a US state! For a list, run `{0}list states`."
msgstr ""

#: ../cogs/covid.py:159
msgid "Didn't find a state with that name! For a list, run `{0}list states`."
msgstr ""

#: ../cogs/covid.py:161
msgid "That isn't a state! Try the `{0}covid {1}` command."
msgstr ""

#: ../cogs/covid.py:177
msgid ""
"I can't send the entire country list: it's over Discord's 6,000 character"
" limit! Try `{0}{1} <letter>` to get only countries starting with "
"`<letter>`."
msgstr ""

#: ../cogs/covid.py:190
msgid ""
"Whatever you have requested, it is over 6,000 characters. I can send a "
"text file, however. React with üìî any time in the next 15 seconds to be "
"DMed a text file instead of a embed."
msgstr ""

#: ../cogs/covid.py:197
msgid "Timed out."
msgstr ""

#: ../cogs/covid.py:202
msgid "Sent you a DM!"
msgstr ""

#: ../cogs/covid.py:204 ../cogs/covid.py:227
msgid "DMed a list to you!"
msgstr ""

#: ../cogs/covid.py:211
msgid "List of {0}"
msgstr ""

#: ../cogs/covid.py:212
msgid "Use `{0}covid {1} <name>` when getting stats for a {1}!"
msgstr ""

#: ../cogs/covid.py:215 ../cogs/covid.py:245
msgid "Name"
msgstr ""

#: ../cogs/covid.py:235
msgid "List of American States"
msgstr ""

#: ../cogs/covid.py:236
msgid "Use the `{0}covid states <name>` command when getting stats for `<name>`!"
msgstr ""

#: ../cogs/covid.py:240 ../cogs/vaccine.py:44
msgid ""
"The page number you have selected is not between 1 and {0}. Please try "
"again."
msgstr ""

#: ../cogs/covid.py:247 ../cogs/covid.py:251 ../cogs/vaccine.py:51
#: ../cogs/vaccine.py:56
msgid "Page {0} of {1}"
msgstr ""

#: ../cogs/covid.py:248 ../cogs/vaccine.py:52
msgid "To go to the next page, run `{0}{1} {2} {3}`"
msgstr ""

#: ../cogs/covid.py:265 ../cogs/covid.py:272
msgid "Incorrect Top List Type"
msgstr ""

#: ../cogs/covid.py:266 ../cogs/covid.py:273
msgid "Try sorting with one of the following:"
msgstr ""

#: ../cogs/covid.py:278
msgid "Top List"
msgstr ""

#: ../cogs/covid.py:279
msgid "Run `{0}help top` for a list of all possible sorts!"
msgstr ""

#: ../cogs/covid.py:281
msgid "{0}: {1}"
msgstr ""

#: ../cogs/database_commands.py:40
msgid "The server prefix is set to `{0}`."
msgstr ""

#: ../cogs/database_commands.py:42
msgid "There is no specific prefix set for this guild."
msgstr ""

#: ../cogs/database_commands.py:60
msgid "The server language is now set to `{0}`."
msgstr ""

#: ../cogs/database_commands.py:66
msgid "There is no specific language set for this guild."
msgstr ""

#: ../cogs/database_commands.py:74
msgid "Tips are currently enabled for this guild."
msgstr ""

#: ../cogs/database_commands.py:76
msgid "Tips are currently disabled for this guild."
msgstr ""

#: ../cogs/database_commands.py:81
msgid "Enabled tips for this guild."
msgstr ""

#: ../cogs/database_commands.py:83
msgid "Disabled tips for this guild."
msgstr ""

#: ../cogs/database_commands.py:97
msgid ""
"The API has been disabled for this channel. To restore your permissions, "
"contact 0/0#0001 on the official support server."
msgstr ""

#: ../cogs/database_commands.py:102
msgid "DMed your API key to you."
msgstr ""

#: ../cogs/database_commands.py:105
msgid "Revoked/deleted API key."
msgstr ""

#: ../cogs/database_commands.py:113
msgid "DMed your new API key to you."
msgstr ""

#: ../cogs/database_commands.py:123
msgid "Disabled the API for {0}."
msgstr ""

#: ../cogs/error_handling.py:72
msgid ""
"There was an error converting one of your arguments with {0}. The correct"
" syntax would be `{1}`. The converter returned the following error: {2}"
msgstr ""

#: ../cogs/error_handling.py:75
msgid "This command is missing an argument. The correct syntax would be `{0}`."
msgstr ""

#: ../cogs/error_handling.py:79
msgid ""
"Too many quotes were provided in your message: don't forget to escape "
"your quotes like this `\\{0}`. The correct syntax for the command is "
"`{1}`."
msgstr ""

#: ../cogs/error_handling.py:85
msgid ""
"A space was expected after a closing quote, but I found {0}. Please check"
" that you are using the correct syntax: `{1}`."
msgstr ""

#: ../cogs/error_handling.py:90
msgid ""
"A closing quote was expected, but wasn't found. Don't forget to close "
"your quotes with `{0}` at the end of your argument. Please check that you"
" are using the correct syntax: `{1}`."
msgstr ""

#: ../cogs/error_handling.py:96
msgid ""
"Too many arguments were passed in this command. Please check that you are"
" using the correct syntax: `{0}`."
msgstr ""

#: ../cogs/error_handling.py:100
msgid ""
"The way you are invoking this command is confusing me. The correct syntax"
" would be `{0}`."
msgstr ""

#: ../cogs/error_handling.py:107
msgid ""
"An argument passed was incorrect. `{0}`.Please check that you are using "
"the correct syntax: `{command_invoke_help}`."
msgstr ""

#: ../cogs/error_handling.py:111
msgid "{0} Please check that you are using the correct syntax: `{1}`."
msgstr ""

#: ../cogs/error_handling.py:120
msgid "This command can only be used in a private message."
msgstr ""

#: ../cogs/error_handling.py:122
msgid "This command cannot be used in a private message."
msgstr ""

#: ../cogs/error_handling.py:124
msgid "Multiple errors were encountered when running your command: {0}"
msgstr ""

#: ../cogs/error_handling.py:127
msgid "You need to be the owner of the bot to run that."
msgstr ""

#: ../cogs/error_handling.py:132
msgid "You are missing permissions to run this command. {0}"
msgstr ""

#: ../cogs/error_handling.py:135
msgid "I am missing permissions to run this command. {0}"
msgstr ""

#: ../cogs/error_handling.py:137
msgid "You are missing the following role: {0}"
msgstr ""

#: ../cogs/error_handling.py:140
msgid "I am missing the following role: {0}"
msgstr ""

#: ../cogs/error_handling.py:144
msgid "You are missing one of the following roles: {0}"
msgstr ""

#: ../cogs/error_handling.py:147
msgid "I am missing one of the following roles: {0}"
msgstr ""

#: ../cogs/error_handling.py:149
msgid "You need to be in a NSFW channel to run that."
msgstr ""

#: ../cogs/error_handling.py:155
msgid "You need to be in the {0} server (`{1}`)."
msgstr ""

#: ../cogs/error_handling.py:160
msgid "You need to be in a server with ID {0}."
msgstr ""

#: ../cogs/error_handling.py:163
msgid "You have the `{0}` permission."
msgstr ""

#: ../cogs/error_handling.py:166
msgid "You need the `{0}` permission."
msgstr ""

#: ../cogs/error_handling.py:169
msgid "You have {0} or more of the following permissions: `{1}`."
msgstr ""

#: ../cogs/error_handling.py:174
msgid "You need {0} or more of the following permissions: `{1}`."
msgstr ""

#: ../cogs/error_handling.py:186
msgid "The provided command was not found."
msgstr ""

#: ../cogs/error_handling.py:188
msgid "That command has been disabled."
msgstr ""

#: ../cogs/error_handling.py:191
msgid ""
"I don't have permissions to send messages there! Try again somewhere I do"
" have permissions to send messages!"
msgstr ""

#: ../cogs/error_handling.py:194
msgid ""
"There was an error running the specified command. This error has been "
"logged."
msgstr ""

#: ../cogs/error_handling.py:210
msgid "You are being ratelimited. Please try again {0}."
msgstr ""

#: ../cogs/error_handling.py:212
msgid "globally"
msgstr ""

#: ../cogs/error_handling.py:213
msgid "per user"
msgstr ""

#: ../cogs/error_handling.py:214
msgid "per guild"
msgstr ""

#: ../cogs/error_handling.py:215
msgid "per channel"
msgstr ""

#: ../cogs/error_handling.py:216
msgid "per member"
msgstr ""

#: ../cogs/error_handling.py:217
msgid "per category"
msgstr ""

#: ../cogs/error_handling.py:218
msgid "per role"
msgstr ""

#: ../cogs/error_handling.py:219
msgid ""
"Too many users are using this command. Only {0} users can use it at the "
"same time {1}."
msgstr ""

#: ../cogs/error_handling.py:222
msgid ""
"Simulations have been disabled in this guild due to a missing permission."
" Ask a admin to give me the Manage Messages permission."
msgstr ""

#: ../cogs/error_handling.py:230
msgid ""
"This should not have happened. A command raised an error that does not "
"comes from CommandError. Please inform the owner."
msgstr ""

#: ../cogs/error_handling.py:235
msgid ""
"\n"
"For help, join the bot's support server at {invite}"
msgstr ""

#: ../cogs/error_handling.py:239
msgid "No message was defined. This error has been logged."
msgstr ""

#: ../cogs/future_simulations.py:66
msgid "Data for Day {0}"
msgstr ""

#: ../cogs/future_simulations.py:100
msgid ""
"**WARNING**\n"
"This is not a scientific modeling system by any means, this purely exists"
" for entertainment purposes. For actual advice, refer to your medical "
"specialist. By agreeing to these terms, you agree not to hold 0/0#0001 "
"liable for anything stemming from the use of this modeling system. Type "
"`ok` within 15 seconds to agree to these terms."
msgstr ""

#: ../cogs/future_simulations.py:109
msgid "Didn't get a response. To try again, do `{0}{1}`."
msgstr ""

#: ../cogs/future_simulations.py:114
msgid "I'll ping you when this is done, you can go do other stuff."
msgstr ""

#: ../cogs/future_simulations.py:115
msgid "Please wait, initializing..."
msgstr ""

#: ../cogs/future_simulations.py:124
msgid ""
"You haven't set up your simulation! Run `{0}simulate setup` to set your "
"sim up!"
msgstr ""

#: ../cogs/future_simulations.py:150
msgid "Submitting your item to be processed..."
msgstr ""

#: ../cogs/future_simulations.py:158
msgid "Waiting for next run of simulation processor, which will happen {0}."
msgstr ""

#: ../cogs/future_simulations.py:162
msgid "Simulation failed: ran out of memory: retry with smaller values."
msgstr ""

#: ../cogs/future_simulations.py:164
msgid ""
"Simulation failed: had incorrect values passed to it: try with more "
"reasonable values."
msgstr ""

#: ../cogs/future_simulations.py:166
msgid ""
"Simulation failed: process running the simulation has failed: ask a mod "
"in the bot's support server (find it via {0}) to run {1}."
msgstr ""

#: ../cogs/future_simulations.py:170
msgid ""
"Simulation failed: had a unknown error: report ID ({0}) to 0/0#0001 to be"
" fixed."
msgstr ""

#: ../cogs/future_simulations.py:180
msgid "Processed simulation!"
msgstr ""

#: ../cogs/future_simulations.py:181
msgid "Simulation Results"
msgstr ""

#: ../cogs/future_simulations.py:182
msgid ""
"Navigate using `next` to view the next day's stats, `prev` to view the "
"previous day's stats, `first` to jump to the first day (tomorrow), and "
"`last` to jump to the last day in your simulation. Type a number to jump "
"straight to that day. Type `exit` to exit the paginator (for example, if "
"you want to modify sim data)."
msgstr ""

#: ../cogs/future_simulations.py:188
msgid "Total infections by end of simulation"
msgstr ""

#: ../cogs/future_simulations.py:189
msgid "Total recoveries by end of simulation"
msgstr ""

#: ../cogs/future_simulations.py:190
msgid "Total deaths by end of simulation"
msgstr ""

#: ../cogs/future_simulations.py:191
msgid "Your simulation is ready: it will be available for 15 minutes."
msgstr ""

#: ../cogs/future_simulations.py:207
msgid "Your simulation has timed out. Request a new one with `{0}{1}`."
msgstr ""

#: ../cogs/future_simulations.py:215
msgid ""
"I now require the MANAGE MESSAGES permission. I've disabled this command "
"until you give me this permission. If you'd prefer not to give me such a "
"permission, the bot will still function, just with the simulation module "
"disabled. Thanks in advance!"
msgstr ""

#: ../cogs/future_simulations.py:236
msgid "Internal bot error. Try again."
msgstr ""

#: ../cogs/future_simulations.py:239
msgid "Out of bounds."
msgstr ""

#: ../cogs/future_simulations.py:252
msgid ""
"You aren't a mod in the bot's support server! You can't run this command."
" If simulations are actually broken, ask a mod in the bot's support "
"server (find it via {0}) to run this command."
msgstr ""

#: ../cogs/future_simulations.py:256
msgid "This could take up to 60 seconds, please wait..."
msgstr ""

#: ../cogs/future_simulations.py:257
msgid "Stopping simulation runners..."
msgstr ""

#: ../cogs/future_simulations.py:266
msgid "Stopping broken process pools..."
msgstr ""

#: ../cogs/future_simulations.py:269
msgid "Waiting 20 seconds for the final tasks to stop..."
msgstr ""

#: ../cogs/future_simulations.py:271
msgid "Destroying pools..."
msgstr ""

#: ../cogs/future_simulations.py:274
msgid "Creating new pools..."
msgstr ""

#: ../cogs/future_simulations.py:277
msgid "Starting up simulation runners..."
msgstr ""

#: ../cogs/future_simulations.py:280
msgid "Restarted pool sucessfully!"
msgstr ""

#: ../cogs/future_simulations.py:287
msgid ""
"Simulation results are very inaccurate after 157 days. I have set the "
"simulation length to 157 days."
msgstr ""

#: ../cogs/future_simulations.py:292
msgid "Set simulation length to {0} days."
msgstr ""

#: ../cogs/graphs.py:19
msgid "Couldn't find that name. Try again, or use `{0}list` for help."
msgstr ""

#: ../cogs/graphs.py:30
msgid ""
"React with üìà for a logarithmic graph.\n"
"React with üìâ for a linear graph.\n"
"This message expires after 30 seconds."
msgstr ""

#: ../cogs/graphs.py:44
msgid "Timed out. Request a new message with `{0}graphs`"
msgstr ""

#: ../cogs/graphs.py:47
msgid "Please wait, this could take a few seconds..."
msgstr ""

#: ../cogs/graphs.py:50
msgid "Graph for {location}"
msgstr ""

#: ../cogs/maps.py:31
msgid "Map Types"
msgstr ""

#: ../cogs/maps.py:32
msgid "Use one of these map types when running `{0}maps show <name>`."
msgstr ""

#: ../cogs/maps.py:47
msgid ""
"I don't know what map you're looking for! Run `{0}maps types` to see all "
"the maps I can show you!"
msgstr ""

#: ../cogs/maps.py:50
msgid "Map for {0}"
msgstr ""

#: ../cogs/maps.py:59
msgid "Updating maps..."
msgstr ""

#: ../cogs/maps.py:61
msgid "Done!"
msgstr ""

#: ../cogs/permissions_commands.py:51
msgid "üòÉ You have that permission."
msgstr ""

#: ../cogs/permissions_commands.py:53
msgid "‚òπÔ∏è You don't have that permission."
msgstr ""

#: ../cogs/permissions_commands.py:56
msgid "Details of permissions hierarchy"
msgstr ""

#: ../cogs/permissions_commands.py:62
msgid "{0} Default (from {0}{1})"
msgstr ""

#: ../cogs/permissions_commands.py:77
msgid "{0} Guild role {1} (from {0}{2})"
msgstr ""

#: ../cogs/permissions_commands.py:87
msgid "{0} Channel role {1} (from {0}{2})"
msgstr ""

#: ../cogs/permissions_commands.py:94
msgid "{0} Member (from {0}{1})"
msgstr ""

#: ../cogs/permissions_commands.py:100
msgid "{0} Fixed (from {0}{1})"
msgstr ""

#: ../cogs/permissions_commands.py:107
msgid "{0} User (from {0}{1})"
msgstr ""

#: ../cogs/permissions_commands.py:130 ../cogs/permissions_commands.py:161
#: ../cogs/permissions_commands.py:188
msgid "**{0} permissions**"
msgstr ""

#: ../cogs/permissions_commands.py:140
msgid "There are no specific permissions set in this guild."
msgstr ""

#: ../cogs/permissions_commands.py:171
msgid "There are no specific permissions set in this channel."
msgstr ""

#: ../cogs/permissions_commands.py:196
msgid "There are no specific permissions for this member."
msgstr ""

#: ../cogs/permissions_commands.py:221
msgid "üëå Permission {0} for user {1} has been set to {2} globally."
msgstr ""

#: ../cogs/permissions_commands.py:237
msgid "üëå Permission {0} for member {1} has been set to {2} globally."
msgstr ""

#: ../cogs/permissions_commands.py:251
msgid "‚ùå Can't set permissions in a channel that is not in this guild."
msgstr ""

#: ../cogs/permissions_commands.py:255 ../cogs/permissions_commands.py:281
msgid "‚ùå Can't set permissions for a role that does not exist in this guild."
msgstr ""

#: ../cogs/permissions_commands.py:268
msgid "üëå Permission {0} for role {1} [`{2}`] has been set to {3} in this channel."
msgstr ""

#: ../cogs/permissions_commands.py:294
msgid "üëå Permission {0} for role {1} [`{2}`] has been set to {3} in this guild."
msgstr ""

#: ../cogs/suggestions.py:31
msgid "Failed to send suggestion due to a Discord error. Try again."
msgstr ""

#: ../cogs/suggestions.py:33
msgid "Sent suggestion successfully."
msgstr ""

#: ../cogs/support_server_commands.py:91
msgid "The bot is not yet sharded."
msgstr ""

#: ../cogs/support_server_commands.py:100
msgid "‚Ä¢\t Shard ID {0}: {1}ms"
msgstr ""

#: ../cogs/support_server_commands.py:102
msgid " (ready)"
msgstr ""

#: ../cogs/support_server_commands.py:104
msgid " This is the current shard"
msgstr ""

#: ../cogs/support_server_commands.py:107
msgid ""
"\n"
"```\n"
"\n"
"Avg latency: {0}ms"
msgstr ""

#: ../cogs/support_server_commands.py:109
msgid " (bot ready)"
msgstr ""

#: ../cogs/utils.py:19
msgid "Credits"
msgstr ""

#: ../cogs/utils.py:28
msgid "current bot version: v5.2.0"
msgstr ""

#: ../cogs/utils.py:29
msgid "v3+ Creator"
msgstr ""

#: ../cogs/utils.py:30
msgid "Original Creator"
msgstr ""

#: ../cogs/utils.py:31
msgid "Bot Framework"
msgstr ""

#: ../cogs/utils.py:32
msgid "Moral Support"
msgstr ""

#: ../cogs/utils.py:33
msgid "API Providers"
msgstr ""

#: ../cogs/utils.py:34
msgid "discord.py Devs"
msgstr ""

#: ../cogs/utils.py:40
msgid "Invite Links"
msgstr ""

#: ../cogs/utils.py:42
msgid "Bot Invite Link"
msgstr ""

#: ../cogs/utils.py:43
msgid "Discord Server Invite Link"
msgstr ""

#: ../cogs/utils.py:61
msgid ""
"I seem to be having issues, apparently I can't find the channel you ran "
"that command in! Please try again."
msgstr ""

#: ../cogs/utils.py:66
msgid "Pong. ‚Äî Time taken: {0}ms"
msgstr ""

#: ../cogs/utils.py:73
msgid "Calling `self.bot.async_setup()`..."
msgstr ""

#: ../cogs/utils.py:75
msgid "Bot has been setup!"
msgstr ""

#: ../cogs/utils.py:79
msgid "Vote Sites"
msgstr ""

#: ../cogs/utils.py:80
msgid ""
"Voting for the bot gives it more visibility, which means it ends up in "
"more servers, giving me (the dev) more incentive to add more features!\n"
"If you want a specific feature, let me know with the `/suggest` command!"
msgstr ""

#: ../cogs/utils.py:91
msgid "**DO NOT disable adblockers!**"
msgstr ""

#: ../cogs/vaccine.py:19
msgid "{0}: {1} candidates\n"
msgstr ""

#: ../cogs/vaccine.py:20
msgid "Vaccine Updates"
msgstr ""

#: ../cogs/vaccine.py:21
msgid ""
"(For more details, run `{0}help vaccine`)\n"
"There are a total of **{1} vaccine candidates**.\n"
"__**Phases**__\n"
"{2}"
msgstr ""

#: ../cogs/vaccine.py:25 ../cogs/vaccine.py:57 ../cogs/vaccine.py:88
#: ../utils/embeds.py:44
msgid "Last updated at"
msgstr ""

#: ../cogs/vaccine.py:35
msgid "Vaccine Candidates"
msgstr ""

#: ../cogs/vaccine.py:36
msgid ""
"To get more details on a vaccine candidate, run `{0}vaccine details <id>`"
"\n"
"The ID of any given candidate is under the name."
msgstr ""

#: ../cogs/vaccine.py:68
msgid "That isn't a valid vaccine ID! View all the IDs in {0}!"
msgstr ""

#: ../cogs/vaccine.py:74
msgid "Description is too long! Download the attachment to see it!"
msgstr ""

#: ../cogs/vaccine.py:78
msgid "Mechanism"
msgstr ""

#: ../cogs/vaccine.py:82
msgid "Sponsors"
msgstr ""

#: ../cogs/vaccine.py:83
msgid "Phase"
msgstr ""

#: ../cogs/vaccine.py:87
msgid "Institutions"
msgstr ""

#: ../utils/embeds.py:30 ../utils/embeds.py:53
msgid "<:infected:775877435320565801> Total Cases"
msgstr ""

#: ../utils/embeds.py:31 ../utils/embeds.py:61
msgid "<:deaths:775877434687488030> Total Deaths"
msgstr ""

#: ../utils/embeds.py:32 ../utils/embeds.py:65
msgid "<:recovered:775877435089748008> Total Recoveries"
msgstr ""

#: ../utils/embeds.py:34
msgid "Province Stats for {province} on {today}"
msgstr ""

#: ../utils/embeds.py:35
msgid ""
"Why such a small amount of data compared to country stats?\n"
"Some provinces may report the same amount of data, but these provinces "
"make up such a small amount of all provinces, meaning it's not worth it "
"to try to show it for all of them."
msgstr ""

#: ../utils/embeds.py:41
msgid "{0} (could also have no data)"
msgstr ""

#: ../utils/embeds.py:54
msgid "New Cases"
msgstr ""

#: ../utils/embeds.py:55
msgid "Cases per 1m People"
msgstr ""

#: ../utils/embeds.py:57
msgid "<:active:775877437056614491> Active Cases"
msgstr ""

#: ../utils/embeds.py:58
msgid "Active Case Change"
msgstr ""

#: ../utils/embeds.py:59
msgid "Active Cases per 1m People"
msgstr ""

#: ../utils/embeds.py:62
msgid "New Deaths"
msgstr ""

#: ../utils/embeds.py:63
msgid "Deaths per 1m People"
msgstr ""

#: ../utils/embeds.py:66
msgid "New Recoveries"
msgstr ""

#: ../utils/embeds.py:67
msgid "Recovered per 1m People"
msgstr ""

#: ../utils/embeds.py:69
msgid "<:tests:775877436075802676> Tests"
msgstr ""

#: ../utils/embeds.py:70
msgid "Tests per 1m People"
msgstr ""

#: ../utils/embeds.py:72
msgid "Critical Cases"
msgstr ""

#: ../utils/embeds.py:73
msgid "Population"
msgstr ""

#: ../utils/embeds.py:90
msgid "COVID-19 Stats for {name}"
msgstr ""

#: ../utils/embeds.py:93
msgid "Stats last updated at (UTC)"
msgstr ""

#: ../utils/embeds.py:106 ../utils/embeds.py:110
msgid "no data"
msgstr ""

#: ../utils/embeds.py:112
msgid "Affected Countries"
msgstr ""

#: ../utils/embeds.py:121
msgid "Country List"
msgstr ""

#: ../utils/embeds.py:122
msgid ""
"Use either the country name, or the ISO2/ISO3 code when getting stats "
"with `/covid <name>`!"
msgstr ""

